version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USER}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5433"